# Generated by Django 4.1.2 on 2022-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="ends_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="starts_at",
            field=models.DateTimeField(null=True),
        ),
    ]
