# Generated by Django 4.1.2 on 2022-10-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attractions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=1000)),
                ("coordinates", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=50)),
                ("bio", models.TextField(max_length=1000)),
                ("tours_count", models.SmallIntegerField()),
                ("is_pro", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("jp", "Японский"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price_rur", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "start_point",
                    models.CharField(blank="", default="", max_length=20, null=True),
                ),
                (
                    "end_point",
                    models.CharField(blank="", default="", max_length=20, null=True),
                ),
                ("children_ok", models.BooleanField(default=True)),
                ("group_size", models.SmallIntegerField()),
                ("attractions", models.ManyToManyField(to="edits.attractions")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edits.city"
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edits.guide"
                    ),
                ),
            ],
        ),
    ]
