# Generated by Django 4.1.2 on 2022-10-26 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.CharField(default="author", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="content",
            field=models.CharField(default="content", max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="tour",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tours.tour"
            ),
            preserve_default=False,
        ),
    ]
