# Generated by Django 4.1.2 on 2022-10-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users_geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users_geography.city",
            ),
        ),
    ]
