# Generated by Django 4.1.2 on 2022-10-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_geography", "0002_alter_user_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"default_related_name": "users", "ordering": ["name"]},
        ),
    ]
