# Generated by Django 4.1.2 on 2022-10-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_geography", "0003_alter_city_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"default_related_name": "users"},
        ),
    ]
