# Generated by Django 4.1.2 on 2022-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("along_neva_channels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="ends_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
