# Generated by Django 4.1.2 on 2022-10-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("along_neva_channels", "0003_tour_author_alter_tour_starts_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="author",
        ),
    ]
